# Generated by Django 2.2.6 on 2019-12-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookgenre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', through='books.BookGenre', to='books.Genre'),
        ),
    ]
