# Generated by Django 2.2.6 on 2019-12-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_edition_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='price',
            field=models.FloatField(),
        ),
    ]
